modLoader = "javafml"
loaderVersion = "[49,)"
issueTrackerURL = "https://github.com/Gjum/snitchmod/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "snitchmod"
version = "${version}"
displayName = "Snitch Mod"
authors = "Gjum"
description = '''
Snitch Mod
'''
#logoFile = ""

[[dependencies.snitchmod]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.snitchmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "CLIENT"
