modLoader = "javafml"
loaderVersion = "[32,)"
#issueTrackerURL = ""
license = "GPL"

[[mods]]
modId = "snitchmod"
version = "${version}"
displayName = "Snitch Mod"
authors = "Gjum"
description = '''
Snitch Mod
'''
#logoFile = ""

[[dependencies.snitchmod]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.snitchmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.1,)"
ordering = "NONE"
side = "CLIENT"
