modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Gjum/snitchmod/issues"
license = "GPL-3.0-only"

[[mixins]]
config="mixin.snitchmod.json"

[[mods]]
modId = "snitchmod"
version = "${version}"
displayName = "Snitch Mod"
authors = "Gjum"
description = '''
Snitch Mod
'''
logoFile = "assets/snitchmod/icon.png"

[[dependencies.snitchmod]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.snitchmod]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "CLIENT"
